In [1]:
# Dependencies
import matplotlib.pyplot as plt
%matplotlib inline

import os
import numpy as np
import pandas as pd

In [2]:
players_csv = "namedPlayers.csv"

In [3]:
players_df = pd.read_csv(players_csv)

In [4]:
players_df.head()

,Unnamed: 0,url,name,active_from,active_to,position,college,height,weight,birth_date,...,NCAA__3ptpg,NCAA_efgpct,NCAA_fgapg,NCAA_fgpct,NCAA_fgpg,NCAA_ft,NCAA_ftapg,NCAA_ftpg,NCAA_games,NCAA_ppg
0,0,/players/a/abdelal01.html,Alaa Abdelnaby,1991,1995,F-C,Duke,6-10,240.0,"June 24, 1968",...,0.0,NaN,5.6,0.599,3.3,0.728,2.5,1.8,134.0,8.5
1,1,/players/a/abdulza01.html,Zaid Abdul-Aziz,1969,1978,C-F,Iowa State,6-9,235.0,"April 7, 1946",...,NaN,NaN,16.8,0.465,7.8,0.645,10.4,6.7,75.0,22.3
2,2,/players/a/abdulka01.html,Kareem Abdul-Jabbar,1970,1989,C,UCLA,7-2,225.0,"April 16, 1947",...,NaN,NaN,16.8,0.639,10.7,0.628,7.9,5.0,88.0,26.4
3,3,/players/a/abdulma02.html,Mahmoud Abdul-Rauf,1991,2001,G,LSU,6-1,162.0,"March 9, 1969",...,2.7,NaN,21.9,0.474,10.4,0.863,6.4,5.5,64.0,29.0
4,4,/players/a/abdulta01.html,Tariq Abdul-Wahad,1998,2003,F,"Michigan, San Jose State",6-6,223.0,"November 3, 1974",...,0.6,NaN,10.4,0.477,4.9,0.726,4.4,3.2,87.0,13.6

In [5]:
stats_df = players_df[['name','height','weight','NCAA__3ptapg','NCAA_fgapg','NCAA_ftapg','NCAA_ppg','NBA__3ptapg','NBA_fga_per_game', 'NBA_fta_p_g','NBA_ppg']]
stats_df.head()

,name,height,weight,NCAA__3ptapg,NCAA_fgapg,NCAA_ftapg,NCAA_ppg,NBA__3ptapg,NBA_fga_per_game,NBA_fta_p_g,NBA_ppg
0,Alaa Abdelnaby,6-10,240.0,0.0,5.6,2.5,8.5,0.0,4.8,1.3,5.7
1,Zaid Abdul-Aziz,6-9,235.0,NaN,16.8,10.4,22.3,NaN,8.2,2.8,9.0
2,Kareem Abdul-Jabbar,7-2,225.0,NaN,16.8,7.9,26.4,0.0,18.1,6.0,24.6
3,Mahmoud Abdul-Rauf,6-1,162.0,7.2,21.9,6.4,29.0,2.3,13.6,2.0,14.6
4,Tariq Abdul-Wahad,6-6,223.0,1.7,10.4,4.4,13.6,0.3,7.3,2.2,7.8

In [6]:
def parse_ht(ht):
    # format: 7' 0.0"
    ht_ = ht.split("-")
    ft_ = float(ht_[0])
    in_ = float(ht_[1])
    return (12*ft_) + in_
    stats_df["height"] = stats_df["height"].apply(parse_ht(ht))

print (stats_df["height"].apply(lambda x:parse_ht(x)))

0       82.0
1       81.0
2       86.0
3       73.0
4       78.0
        ...
4980    82.0
4981    85.0
4982    73.0
4983    84.0
4984    75.0
Name: height, Length: 4985, dtype: float64

In [7]:
stats_df["height"] = stats_df["height"].apply(lambda x:parse_ht(x))
stats_df.head()

<ipython-input-7-8a66c1c1f821>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats_df["height"] = stats_df["height"].apply(lambda x:parse_ht(x))

,name,height,weight,NCAA__3ptapg,NCAA_fgapg,NCAA_ftapg,NCAA_ppg,NBA__3ptapg,NBA_fga_per_game,NBA_fta_p_g,NBA_ppg
0,Alaa Abdelnaby,82.0,240.0,0.0,5.6,2.5,8.5,0.0,4.8,1.3,5.7
1,Zaid Abdul-Aziz,81.0,235.0,NaN,16.8,10.4,22.3,NaN,8.2,2.8,9.0
2,Kareem Abdul-Jabbar,86.0,225.0,NaN,16.8,7.9,26.4,0.0,18.1,6.0,24.6
3,Mahmoud Abdul-Rauf,73.0,162.0,7.2,21.9,6.4,29.0,2.3,13.6,2.0,14.6
4,Tariq Abdul-Wahad,78.0,223.0,1.7,10.4,4.4,13.6,0.3,7.3,2.2,7.8

In [8]:
stats_df.to_csv("stats.csv", encoding="utf-8", index=True)